spring.application.name=api-gateway
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8010/eureka
# --Automatic Mapping of Gateway Routes--
# Enable Discovery locator
#spring.cloud.gateway.discovery.locator.enabled=true
# To access service with lower case in url
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# --Manually Configuring API Gateway Routes--
spring.cloud.gateway.routes[0].id=users-status-check
spring.cloud.gateway.routes[0].uri=lb://users-ws
spring.cloud.gateway.routes[0].predicates[0]=Path=/users-ws/users/status/check
spring.cloud.gateway.routes[0].predicates[1]=Method=GET
spring.cloud.gateway.routes[0].predicates[2]=Header=Authorization, Bearer (.*)
spring.cloud.gateway.routes[0].filters[0]=RemoveRequestHeader=Cookie
# 将第一个参数的path路由到第二个参数的path。
# api gateway收到请求localhost:8082/users-ws/users/status/check之后，会rewrite到localhost:8082/users/status/check
spring.cloud.gateway.routes[0].filters[1]=RewritePath=/users-ws/users/status/check, /users/status/check
# 在路由至/users-ws/users/status/check之前，需要先触发AuthorizationHeaderFilter这个filter：
spring.cloud.gateway.routes[0].filters[2]=AuthorizationHeaderFilter

# sign up/create a user. Filter is not needed
spring.cloud.gateway.routes[1].id=users-ws
spring.cloud.gateway.routes[1].uri=lb://users-ws
spring.cloud.gateway.routes[1].predicates[0]=Path=/users-ws/users
spring.cloud.gateway.routes[1].predicates[1]=Method=POST
spring.cloud.gateway.routes[1].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.routes[1].filters[1]=RewritePath=/users-ws/users, /users

spring.cloud.gateway.routes[2].id=users-ws-h2-console
spring.cloud.gateway.routes[2].uri=lb://users-ws
spring.cloud.gateway.routes[2].predicates[0]=Path=/users-ws/h2-console
spring.cloud.gateway.routes[2].predicates[1]=Method=GET
spring.cloud.gateway.routes[2].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.routes[2].filters[1]=RewritePath=/users-ws/(?<segment>.*), /${segment}

# login。此时还没有JWT token，所以访问这个端点时，也无法authenticate，不需要经过filter。登录是为了获取 Token
spring.cloud.gateway.routes[3].id=users-ws-login
spring.cloud.gateway.routes[3].uri=lb://users-ws
spring.cloud.gateway.routes[3].predicates[0]=Path=/users-ws/users/login
spring.cloud.gateway.routes[3].predicates[1]=Method=POST
spring.cloud.gateway.routes[3].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.routes[3].filters[1]=RewritePath=/users-ws/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[4].id=users-ws-get-update-delete
spring.cloud.gateway.routes[4].uri=lb://users-ws
spring.cloud.gateway.routes[4].predicates[0]=Path=/users-ws/users/**
spring.cloud.gateway.routes[4].predicates[1]=Method=GET,PUT,DELETE
spring.cloud.gateway.routes[4].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.routes[4].filters[1]=RewritePath=/users-ws/(?<segment>.*), /${segment}
# 在路由至/users-ws/users/**且Method=GET,PUT,DELETE前，需要先触发AuthorizationHeaderFilter这个filter：
spring.cloud.gateway.routes[4].filters[2]=AuthorizationHeaderFilter

# Users Microservice Actuator Routing
spring.cloud.gateway.routes[5].id=users-ws-actuator
spring.cloud.gateway.routes[5].uri=lb://users-ws
spring.cloud.gateway.routes[5].predicates[0]=Path=/users-ws/actuator/**
spring.cloud.gateway.routes[5].predicates[1]=Method=GET
spring.cloud.gateway.routes[5].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.routes[5].filters[1]=RewritePath=/users-ws/(?<segment>.*), /${segment}

# http://localhost:8012 is a domain and port on which Config Server is running
# 启动时，从指定地址 http://localhost:8012 的 Spring Config Server 拉取远程配置。
# optional: 如果 Config Server 不可用，应用 仍然可以启动
spring.config.import=optional:configserver:http://localhost:8012

# rabbitmq configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# 启用 gateway 端点（非默认启用，需显式开启）（health是默认启用的，所以不用开启）
management.endpoint.gateway.enabled=true
# 通过 HTTP 暴露以下端点（多个用逗号分隔）
management.endpoints.web.exposure.include=gateway,health,mappings
# 若要暴露所有端点（开发环境用，生产环境慎用）：
# management.endpoints.web.exposure.include=*