spring.application.name=account-ws

# assign port number automatically
server.port=0
#eureka.instance.hostname=localhost

# Eureka Client ??
# This is the port number specified in Eureka server --8010
eureka.client.service-url.defaultZone=http://localhost:8010/eureka

# if you have multiple eureka servers for high availability, then set this value to true.
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=true

# Eureka Instance ??
#eureka.instance.preferIpAddress=true
#eureka.instance.instance-id=${spring.application.name}:${random.value}
#eureka.instance.leaseRenewalIntervalInSeconds=10
#eureka.instance.leaseExpirationDurationInSeconds=30

# Spring DevTools ??
# To restart and redeploy the application automatically when we make changes to codes
spring.devtools.restart.enabled=true

# rabbitmq configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest