spring.application.name=PhotoAppDiscoveryService
server.port=8010
eureka.instance.hostname=localhost

# if you have multiple eureka servers for high availability, then set this value to true.
eureka.client.register-with-eureka=false

# This is the url of eureka server that this application will use to register and discover other services
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka
eureka.instance.preferIpAddress=true